# Site settings
title: XueChangwu
SEOTitle: XueChangwu.github.io | canada.air
header-img: img/post-bg-desk.jpg
email: changwucanada.air312@foxmail.com
description: ğŸ‡¨ğŸ‡¦ğŸ‡¨ğŸ‡¦He is an assistant HRD manager at Air Canada Shanghai Office [7 years of work experience] [full course industry] A If the interviewer has any questions, you can consult me. B If you have a resume, you can find me. Has a high pass rate for resumes. I can help you with resumes because I know what HR needs to focus on. I can also use my resources to help you deliver resumes to the list of the world â€™s top 500 companies.
æˆ‘æ˜¯ä¸€ååœ¨åŠ æ‹¿å¤§èˆªç©ºä¸Šæµ·åŠäº‹å¤„HRDç»ç†åŠ©ç†ã€æœ‰7å¹´å·¥ä½œç»éªŒã€‘ã€å…¨ç§‘è¡Œä¸šã€‘A å¦‚æœé¢è¯•è€…æœ‰ä»€ä¹ˆä¸æ‡‚å¾—åœ°æ–¹å¯ä»¥å’¨è¯¢æˆ‘ .B å¦‚æœæœ‰ç®€å†ä¸æ˜ç™½åœ°æ–¹å¯ä»¥æ‰¾æˆ‘.æˆ‘åšçš„ç®€å†é€šè¿‡ç‡å¾ˆé«˜.æˆ‘å¯ä»¥å¸®ä½ ä»¬åšç®€å†å› ä¸ºæˆ‘çŸ¥é“HRéœ€è¦çœ‹ä»€ä¹ˆé‡ç‚¹.è¿˜å¯ä»¥ç”¨æˆ‘çš„èµ„æºå¸®ä½ ä»¬æŠ•é€’ç®€å†åˆ°ä¸–ç•Œäº”ç™¾å¼ºä¼ä¸šåå•é‡Œ.ï¼ˆæ‰€ä»¥è¡Œä¸šéƒ½å¯ä»¥åšç®€å†)

keyword: äººåŠ›èµ„æº . è¾¾ç¾èˆªç©ºå…¬å¸ . åŠ æ‹¿å¤§èˆªç©º. ç®€å†. æŠ¤è‚¤å“ . æ—…è¡Œ. èµ„æº .  Hyatt Hotels Corporation . Ritz-Carlton . Four Seasons . The Peninsula Hotels .Fairmont Hotels & Resorts . å¥¢ä¾ˆå“ . FAå¹¿å‘Š . åª’ä½“ . åŒ»ç–—
url: "https://xuechangwu.github.io/"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/XueChangwu/XueChangwu.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Goals determine what you going to be!"
sidebar-avatar: /img/about-BY-gentle.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     qiubaiying
zhihu_username:     qiubaiying
github_username:    qiubaiying
facebook_username:  baiying.qiu.7
jianshu_username:   e71990ada2fd
#twitter_username:   qiubaiying




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# è¯„è®ºç³»ç»Ÿ
# Disqusï¼ˆhttps://disqus.com/ï¼‰
# disqus_username: qiubaiying

# Gitalk
gitalk:
  enable: true    #æ˜¯å¦å¼€å¯Gitalkè¯„è®º
  clientID: f2c84e7629bb1446c1a4                            #ç”Ÿæˆçš„clientID
  clientSecret: ca6d6139d1e1b8c43f8b2e19492ddcac8b322d0d    #ç”Ÿæˆçš„clientSecret
  repo: qiubaiying.github.io    #ä»“åº“åç§°
  owner: qiubaiying    #githubç”¨æˆ·å
  admin: qiubaiying
  distractionFreeMode: true #æ˜¯å¦å¯ç”¨ç±»ä¼¼FBçš„é˜´å½±é®ç½©


# ç»Ÿè®¡

# Analytics settings
# Baidu Analytics
ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
ga_domain: qiubaiying.top               # é»˜è®¤çš„æ˜¯ auto, è¿™é‡Œæˆ‘æ˜¯è‡ªå®šä¹‰äº†çš„åŸŸåï¼Œä½ å¦‚æœæ²¡æœ‰è‡ªå·±çš„åŸŸåï¼Œéœ€è¦æ”¹æˆauto





# Featured Tags
featured-tags: true                     # æ˜¯å¦ä½¿ç”¨é¦–é¡µæ ‡ç­¾
featured-condition-size: 1              # ç›¸åŒæ ‡ç­¾æ•°é‡å¤§äºè¿™ä¸ªæ•°ï¼Œæ‰ä¼šå‡ºç°åœ¨é¦–é¡µ



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "WY",
        href: "http://zhengwuyang.com"
    },{
        title: "ç®€ä¹¦Â·BY",
        href: "http://www.jianshu.com/u/e71990ada2fd"
    },{
        title: "Apple",
        href: "https://apple.com"
    },{
        title: "Apple Developer",
        href: "https://developer.apple.com/"
    }
]
